### ISSUE TITLE
[Bug] Crashes on app start on armv7 (Oreo)

### ISSUE THREAD

**Issue by ni554n** [Dr-TSNG/TwiFucker#100]
### Steps to reproduce/复现步骤

Download and install the LSPatched version from Telegram

### Expected behaviour/预期行为

App should start normally

### Actual behaviour/实际行为

Crashes on start after installation

### Xposed Module List/Xposed 模块列表

```Shell
LSPatch
```

### TwiFucker version/TwiFucker 版本

V1.9.r182.e1d22ee-debug

### Twitter version/Twitter 版本

9.72.0

### Android version/Android 版本

8.1

### Xposed Framework/Xposed 框架

LSPatch

### Framework version/框架版本

https://github.com/LSPosed/LSPatch/commit/9846b3ff97f9880a283a7562d0f8d04ae269e8a2

### Version requirement/版本要求

Public release/beta version/公开发布/测试版

### Logs/日志

```kotlin
FATAL EXCEPTION: main
  Process: com.twitter.android, PID: 2306
  java.lang.RuntimeException: Unable to instantiate application com.twitter.app.TwitterApplication: java.lang.ClassNotFoundException: Didn't find class "com.twitter.app.TwitterApplication" on path: DexPathList[[zip file "/data/app/com.twitter.android-Xjw_xLwLUWo2o75olnrolw==/base.apk"],nativeLibraryDirectories=[/data/app/com.twitter.android-Xjw_xLwLUWo2o75olnrolw==/lib/arm, /data/app/com.twitter.android-Xjw_xLwLUWo2o75olnrolw==/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
   at android.app.LoadedApk.makeApplication(LoadedApk.java:989)
   at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5730)
   at android.app.ActivityThread.-wrap1(Unknown Source:0)
   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1659)
   at android.os.Handler.dispatchMessage(Handler.java:106)
   at android.os.Looper.loop(Looper.java:164)
   at android.app.ActivityThread.main(ActivityThread.java:6518)
   at java.lang.reflect.Method.invoke(Native Method)
   at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
  Caused by: java.lang.ClassNotFoundException: Didn't find class "com.twitter.app.TwitterApplication" on path: DexPathList[[zip file "/data/app/com.twitter.android-Xjw_xLwLUWo2o75olnrolw==/base.apk"],nativeLibraryDirectories=[/data/app/com.twitter.android-Xjw_xLwLUWo2o75olnrolw==/lib/arm, /data/app/com.twitter.android-Xjw_xLwLUWo2o75olnrolw==/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
   at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
   at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
   at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
   at android.app.Instrumentation.newApplication(Instrumentation.java:1088)
   at android.app.LoadedApk.makeApplication(LoadedApk.java:983)
   at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5730) 
   at android.app.ActivityThread.-wrap1(Unknown Source:0) 
   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1659) 
   at android.os.Handler.dispatchMessage(Handler.java:106) 
   at android.os.Looper.loop(Looper.java:164) 
   at android.app.ActivityThread.main(ActivityThread.java:6518) 
   at java.lang.reflect.Method.invoke(Native Method) 
   at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) 
   Suppressed: java.io.IOException: Failed to open dex files from /data/app/com.twitter.android-Xjw_xLwLUWo2o75olnrolw==/base.apk because: Unrecognized version number in /data/app/com.twitter.android-Xjw_xLwLUWo2o75olnrolw==/base.apk: 0 3 9 
    at dalvik.system.DexFile.openDexFileNative(Native Method)
    at dalvik.system.DexFile.openDexFile(DexFile.java:353)
    at dalvik.system.DexFile.<init>(DexFile.java:100)
    at dalvik.system.DexFile.<init>(DexFile.java:74)
    at dalvik.system.DexPathList.loadDexFile(DexPathList.java:374)
    at dalvik.system.DexPathList.makeDexElements(DexPathList.java:337)
    at dalvik.system.DexPathList.<init>(DexPathList.java:157)
    at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:65)
    at dalvik.system.PathClassLoader.<init>(PathClassLoader.java:64)
    at com.android.internal.os.ClassLoaderFactory.createClassLoader(ClassLoaderFactory.java:73)
    at com.android.internal.os.ClassLoaderFactory.createClassLoader(ClassLoaderFactory.java:88)
    at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:69)
    at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:35)
    at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:693)
    at android.app.LoadedApk.getClassLoader(LoadedApk.java:727)
    at android.app.LoadedApk.getResources(LoadedApk.java:954)
    at android.app.ContextImpl.createAppContext(ContextImpl.java:2286)
    at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5654)
    ... 8 more
```

**Comment by JasonKhew96** [comment]
forgot to mention, LSPatch only support Android 9 and above
